// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYv46aSlbhKlLaS9474Ljv3x1B3BieTCw',
    appId: '1:101238677078:web:c600698da0f25109cf25f7',
    messagingSenderId: '101238677078',
    projectId: 'raseed-ai-backend',
    authDomain: 'raseed-ai-backend.firebaseapp.com',
    storageBucket: 'raseed-ai-backend.firebasestorage.app',
    measurementId: 'G-2BD7X2PL8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemo-ANDROID-API-KEY-FOR-DEVELOPMENT',
    appId: '1:123456789:android:abcdef123456789',
    messagingSenderId: '123456789',
    projectId: 'raseed-demo-project',
    storageBucket: 'raseed-demo-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemo-IOS-API-KEY-FOR-DEVELOPMENT',
    appId: '1:123456789:ios:abcdef123456789',
    messagingSenderId: '123456789',
    projectId: 'raseed-demo-project',
    storageBucket: 'raseed-demo-project.appspot.com',
    iosBundleId: 'com.example.uiNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemo-MACOS-API-KEY-FOR-DEVELOPMENT',
    appId: '1:123456789:ios:abcdef123456789',
    messagingSenderId: '123456789',
    projectId: 'raseed-demo-project',
    storageBucket: 'raseed-demo-project.appspot.com',
    iosBundleId: 'com.example.uiNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDemo-WINDOWS-API-KEY-FOR-DEVELOPMENT',
    appId: '1:123456789:web:abcdef123456789',
    messagingSenderId: '123456789',
    projectId: 'raseed-demo-project',
    authDomain: 'raseed-demo-project.firebaseapp.com',
    storageBucket: 'raseed-demo-project.appspot.com',
    measurementId: 'G-ABCDEF123456',
  );
}
